name: Shel Maala
byline: A Digital-First, Queer Yeshiva
url: https://shelmaala.com
donateString: bkoatz@gmail.com
homeImage: https://i.imgur.com/Avf6BWi.jpg
aboutSummary: Shel Maala is a digital-first queer Yeshiva, founded in
  5781(/2020), in the deep belly of the Covid-19 Pandemic. Our dream is to serve
  as a fully-stocked, radically irreverent, unapologetically gay Yeshiva in
  cyberspace, so that every Jew who can access the internet can access joyful,
  raucous, soul-enlivening queer Talmud, 24/6 (minus shabbes!).
aboutText: >-
  Shel Maala is a digital-first queer Yeshiva, founded in 5781(/2020), in the
  deep belly of the Covid-19 Pandemic. Our dream is to serve as a fully-stocked,
  radically irreverent, unapologetically gay Yeshiva in cyberspace, so that
  every Jew who can access the internet can access joyful, raucous,
  soul-enlivening queer Talmud, 24/6 (minus shabbes).


  Our name is derived from the phrase "Yeshiva Shel Maala," the Yeshiva in the Clouds, which we believe is the most nerdy, gay and Jewish conception of heaven - that after we die (ad mea v'esrim!) our reward for a life of studying Talmud, is an eternity of, you guessed it --- studying more Talmud!!


  As proud members of the virtual "cloud" (get it?!), we aim to be at the forefront of the digital Queer Talmud revolution, which has flourished over the past several years as much of the rest of the world - queer, Jewish, and otherwise - has moved its content to an online format to make it accessible through the pandemic. We want to ensure that the accessibility and electronic community crafted over the course of this crisis continue long after it is gone.


  In that same vein, Shel Maala  is a normatively anti-zionist yeshiva. Our institutional viewpoint, norms and principles are anti-zionist. We believe that anti-zionist students shouldn’t have  to compromise their commitments to diasporism and Palestinian liberation to access Jewish learning, and we want to be their Jewish learning home. Regardless, our Yeshiva remains open to all. Just as anti-zionist students often navigate zionist Jewish spaces to get the Jewish learning they crave, zionist students are also welcome to respectfully navigate an anti-zionist space here. 


  Just like our mama Yeshiva, [Svara](https://svara.org/), our purpose is to uplift the prophetic Torah already bubbling out of the margins of Jewish society, and hone it, through hardcore praxis, into a world-altering force that can overturn mountains. We are proud to play a small part within the symbiotic biome of Queer Talmud currently flourishing across the world, and dream of a diaspora where the radical pedagogy of Svara-style teaching can be found in every corner of that globe - both physical, and virtual.


  # A﻿bout Xava and Binya


  **Rabbi Xava De Cordova** is a disabled, Sefradi, Mizraxi trans woman and co-host of the world's first Queer Talmud podcast, "Xai, how are you?". She is a long-time SVARA-style Talmud learner and SVARA teaching kollel fellow who got her start as a teacher by creating Beit Midrash Behind Bars, an organization that facilitated Jewish learning opportunities for incarcerated people in Washington State. She is also the co-Rosh Yeshiva of Shel Maala, which she co-founded with her incredible co-Rosh, Binya. She lives in Providence, RI, where she regularly produces Jewish ritual theatre (or did, before the pandemic) and does her best to steward the radical tradition she's been blessed to inherit.


  **Binya Kóatz** is a sefardi / ashki / moroccan / argentinean / ukranian / french trans jewish torah-lover, who writes poetry, organizes jewish community and sings and dances with her foremothers. She is originally from the alte heim in Queens, she currently splits her time between Ohlone Land in the East Bay and the island of Montréal, Mooniyang, Tiohtiá:ke in Québec, Canada. In addition to running this Yeshiva, she teaches private students, sings in a klezmer band, does standup as @binya_donethat and drag as @auntie.semitism
